# Generated by Django 5.1.2 on 2024-10-26 11:34

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_category_portfoliocategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=250)),
                ('name_uz', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('sku', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Images/product')),
                ('main_information', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('dimension', models.TextField()),
                ('purchased_place', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('shipping', models.BigIntegerField()),
                ('care_info', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.productcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioCategory',
        ),
    ]
